name: Assignment 2 [Build, test, deploy]

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
    
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
    
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.dockerhub_username }}
           password: ${{ secrets.dockerhub_password }}
     
       - name: Build and push
         uses: docker/build-push-action@v4
         with:
           push: true
           tags: ${{ secrets.dockerhub_username }}/s2:v1
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      -
        name: Test my app
        working-directory: ./
        run: |
          echo "START"
          pip install -r req.txt
          python test_app.py
          echo "STOP"
